# Generated by Django 4.2.6 on 2023-10-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0003_alter_student_id_alter_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sId',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tId',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
