# Generated by Django 4.2.6 on 2023-10-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0004_student_sid_teacher_tid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sId',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='tId',
        ),
    ]
